# Generated by Django 3.2.6 on 2021-09-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210909_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(default=None, help_text='tag url', max_length=50),
            preserve_default=False,
        ),
    ]
