# Generated by Django 3.2.6 on 2021-09-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
    ]
