# Generated by Django 3.2.6 on 2021-09-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210909_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Author of comment', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of comment')),
                ('comment_text', models.TextField(help_text='Comment text')),
                ('email', models.CharField(help_text="Author's email", max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
